version: '3.8'

services:
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dishto_celery
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - qdrant
      - postgres
      - redis
    command: celery -A dishto worker --loglevel=info --concurrency=1 --pool=solo
    networks:
      - dishto-net
    healthcheck:
      test: ["CMD", "celery", "-A", "dishto", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  postgres:
    image: postgres:15
    container_name: dishto_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${INIT_PATH:-./init}:/docker-entrypoint-initdb.d:ro
    networks:
      - dishto-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PG_USER} -d $${PG_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7
    container_name: dishto_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"      
    networks:
      - dishto-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  qdrant:
    image: qdrant/qdrant
    container_name: dishto_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT_ALLOW_ORIGIN=*
    volumes:
      - qdrant_data:/qdrant/storage
      - ./src/snapshots:/snapshots:ro
    mem_limit: 256m
    cpus: 0.2
    networks:
      - dishto-net

volumes:
  postgres_data:
  redis_data:
  qdrant_data:

networks:
  dishto-net:
    driver: bridge
